### ISSUE TITLE
HealthAssistant F-Droid package encouragement

### ISSUE THREAD

**Issue by davidhedlund** [isaakhanimann/psychonautwiki-journal-android#1]
HealthAssistant is useful, but it is not yet distributed on any mobile software distribution platform. F-Droid is a software distribution platform for Android that focus on free software unlike Google Play. So it has ethical advantages.

Please read https://f-droid.org/docs/Submitting_to_F-Droid_Quick_Start_Guide/ for more information.

**Comment by jaromeyer** [comment]
I'll try to have a look at it since I also have another app that I plan on publishing on F-Droid anyway.

**Comment by isaakhanimann** [comment]
@jaromeyer any update?

**Comment by jaromeyer** [comment]
@isaakhanimann sorry for the late answer. I've been pretty busy with work and some other projects, so unfortunately I wasn't able to make any progress on this yet. It's still on my todo list tho (unless you or someone else wants to do it ofc😄)

**Comment by Jeidnx** [comment]
I've looked into this a bit and there need to be some changes before this Project can be accepted into the F-Droid repo. These dependencies are non-free and not allowed there:
 - crashlytics
 - firebase
 - play-services

I can't judge how much work it would be to remove / replace these dependencies and most likely won't be able to help with this since i am not an Android developer.

In the meantime #55 was merged and (if all goes well) there will be Github releases starting with the next version. One could use tools such as [Obtainium](https://github.com/ImranR98/Obtainium) to avoid the Google Playstore.

**Comment by isaakhanimann** [comment]
I think I will remove those dependencies now. The main drawback is that if there is no Crashlytics in the app anymore then I won't be able to see why the app is crashing if because of a bug a lot of users experience app crashes.
Its a risk but I think I would do it anyway.

**Comment by isaakhanimann** [comment]
@Jeidnx I removed the dependencies you mentioned.

**Comment by davidhedlund** [comment]
> I think I will remove those dependencies now. The main drawback is that if there is no Crashlytics in the app anymore then I won't be able to see why the app is crashing if because of a bug a lot of users experience app crashes. Its a risk but I think I would do it anyway.

I just found out that [ACRA](https://github.com/ACRA/acra/) is a F-Droid compatible crash reporting framework. Check it out!

**Comment by davidhedlund** [comment]
> > I think I will remove those dependencies now. The main drawback is that if there is no Crashlytics in the app anymore then I won't be able to see why the app is crashing if because of a bug a lot of users experience app crashes. Its a risk but I think I would do it anyway.
> 
> I just found out that [ACRA](https://github.com/ACRA/acra/) is a F-Droid compatible crash reporting framework. Check it out!

For more ideas, have a look at [FOSS Crash Reporting Tools](https://forum.f-droid.org/t/foss-crash-reporting-tools/3457)

**Comment by Jeidnx** [comment]
I have opened a Merge Request, if anyone wants to take a look: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/16063

**Comment by davidhedlund** [comment]
Add label "high priority" to this issue?

**Comment by Jeidnx** [comment]
The F-Droid CI found some issues with the Gradle setup. It notes that the wrapper is not the same version as specified and recommends adding distribution checksums to the gradle properties.  
The CI results also include simple instructions to resolve this ([link](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/16063#note_2168191935), see section 'Gradle Wrapper').

I am not sure if this is required to get the app into the F-Droid repo, but it seems like a good idea to me in any case. I have also verified that the build produced by their CI matches the one built by Github bit-for-bit, so we should be on the home stretch now

**Comment by isaakhanimann** [comment]
I added the distribution checksum and updated the gradle wrapper as it suggested in the instructions. I created a new release v8.13. Can you try to publish to f-droid again?

**Comment by GrahamxReed** [comment]
I am in your interwebs, sending ethereal support vibrations. (づ｡◕‿‿◕｡)づ

**Comment by Jeidnx** [comment]
I just got some feedback that the [short description](https://github.com/isaakhanimann/psychonautwiki-journal-android/blob/bd5ba424abae0add29a24da1c205dcb23a8a1503/metadata/en-US/short_description.txt) is too long. A maximum of 80 characters is allowed. I would recommend something along the lines of
> _Keep track of substance usage to gain insights on consumption patterns_

Notably, I'm pretty sure the short description shouldn't include the app name itself. At least i noticed that with other apps.

**Comment by isaakhanimann** [comment]
Sounds good. I'll update it later today

**Comment by isaakhanimann** [comment]
I just updated the short description to your suggestion and created a new release.

**Comment by davidhedlund** [comment]
Can you please reply to this message when the release is available at https://f-droid.org/ to inform everyone? @isaakhanimann

**Comment by isaakhanimann** [comment]
> Can you please reply to this message when the release is available at https://f-droid.org/ to inform everyone? @isaakhanimann

Its available now

**Comment by davidhedlund** [comment]
> > Can you please reply to this message when the release is available at https://f-droid.org/ to inform everyone? @isaakhanimann
> 
> Its available now

Thanks: https://f-droid.org/en/packages/com.isaakhanimann.journal/

**Comment by isaakhanimann** [comment]
@Jeidnx do you know why f-droid still shows v8.17?

I'd rather not have an f-droid release at all then have an outdated one.

**Comment by Jeidnx** [comment]
I think it can take up to a week or so for F-Droid to update the app. The metadata was already updated to version 9.2 now the builder needs to pick the job up.

**Comment by davidhedlund** [comment]
> Oh ok. Thanks for the info. Will check later then.

"It took 14 days between the release of OpenTracks v3.15.0 and it’s availability on F-Droid." - https://forum.f-droid.org/t/how-long-for-an-app-to-be-available-for-download-once-metadata-are-updated/12740/7
