### ISSUE TITLE
Poppers: Overdose via oral ingestion can lead to death. Amyl or butyl nitrites may cause lipoid pneumonia.

### ISSUE THREAD

**Issue by davidhedlund** [isaakhanimann/psychonautwiki-journal-android#10]
[Poppers](https://psychonautwiki.org/wiki/Poppers): An overdose via oral ingestion alkyl nitrites can lead to methemoglobinemia, coma, and death.[[10]](https://psychonautwiki.org/wiki/Unique_substance_warnings#cite_note-Medsafe-10)[[11]](https://psychonautwiki.org/wiki/Unique_substance_warnings#cite_note-Dixon-1981-11)[[12]](https://psychonautwiki.org/wiki/Unique_substance_warnings#cite_note-Pruijm-2002-12)[[13]](https://psychonautwiki.org/wiki/Unique_substance_warnings#cite_note-13)[[14]](https://psychonautwiki.org/wiki/Unique_substance_warnings#cite_note-14) Accidental aspiration of amyl or butyl nitrites may cause lipoid pneumonia.[[15]](https://psychonautwiki.org/wiki/Unique_substance_warnings#cite_note-Hagan--15)

Title: Poppers
Author: Multiple authors
Source: https://psychonautwiki.org/wiki/Poppers, https://wikipedia.org/wiki/Poppers
License: Creative Commons Attribution-ShareAlike 4.0 International

**Comment by isaakhanimann** [comment]
In the Poppers safer use text it already says that one should not ingest it orally.

**Comment by davidhedlund** [comment]
> In the Poppers safer use text it already says that one should not ingest it orally.

Please mention that it can cause death.

**Comment by isaakhanimann** [comment]
It already says that.
