### ISSUE TITLE
Routes of administration: Vaporizing/smoking: Chasing the dragon (foiling) is dangerous

### ISSUE THREAD

**Issue by davidhedlund** [isaakhanimann/psychonautwiki-journal-android#14]
If people are selecting smoking or vaporizing, a small box with text that warns about **chasing the dragon (foiling)** should appear, because it is difficult to not burn the substance.

[Chasing the dragon (foiling)](https://psychonautwiki.org/wiki/Routes_of_administration)
"This is likely the least clinically delivered route of administration. An overdose caused by chasing the dragon is hard to predict because this technique doesn't deliver a standardized dosage. It's virtually impossible even for skilled users to know how much of the substance that has been evaporated, burned, and inhaled.

These combined factors may create a false sense of security when a given dose seems safe to repeat, but may cause an overdose when all the factors are randomly excluded."

Title: Routes of administration
Author: David Hedlund
Source: https://psychonautwiki.org/wiki/Routes_of_administration
License: Creative Commons Attribution-ShareAlike 4.0 International

**Comment by isaakhanimann** [comment]
Added this to ChooseDoseScreen and SubstanceScreen.
