### ISSUE TITLE
[UI] limit quick logging

### ISSUE THREAD

**Issue by jaromeyer** [isaakhanimann/psychonautwiki-journal-android#24]
After some time the quick logging card can become quite cluttered. I don't want to see options for 18mg, 19 mg, 20 mg, 21 mg and 22 mg just because I'm unable to weigh exactly 20 mg every time. Maybe consider making the card a bit more compact and show only the last k doses or k most used doses for every substance.

**Comment by isaakhanimann** [comment]
Its already limited to the 6 last distinct doses. Now with the search also filtering the suggestions the screen is less cluttered anyway.

**Comment by jaromeyer** [comment]
oh sorry, didn't notice that. and the new add substance screen works great!

**Comment by isaakhanimann** [comment]
Thank you!
