### ISSUE TITLE
[FEATURE] add timestamped notes during experience

### ISSUE THREAD

**Issue by jaromeyer** [isaakhanimann/psychonautwiki-journal-android#25]
Currently the 'Add Notes' button just opens the edit experience screen where the user can write a single note for the whole experience. For me it would make more sense if the button created a new note with the current timestamp and the experience screen would show a vertical timeline of all events (notes, ingestions, shulgin rating).

**Comment by isaakhanimann** [comment]
Implemented this in the past couple of weeks.
