### ISSUE TITLE
FloatingActionButton obstructing the view when noting on Edit Experience page

### ISSUE THREAD

**Issue by Zipos** [isaakhanimann/psychonautwiki-journal-android#26]
Hi, I'm new to this repo. I have used the app for a while and I'm a big fan overall but I noticed that when you take notes, there is an annoying bug of not seeing what you type as you approach the bottom of the text field.

This could be resolved by:
- Making the floating action button hide itself when keyboard is on the screen
- Moving the button to the top bar
- Ditching this type of notes and replacing it with timed ones similar to or inside the Shulgin rating page (also requested in #25)

![Screenshot_20230525-215326_Journal](https://github.com/isaakhanimann/psychonautwiki-journal-android/assets/74840471/66e19c29-d049-4a18-b927-896126446f2e)

**Comment by isaakhanimann** [comment]
Thank you!
