### ISSUE TITLE
Updating substances.json

### ISSUE THREAD

**Issue by Im-0xea** [isaakhanimann/psychonautwiki-journal-android#29]
Hyia!

I have been playing around a bit with your wonderful app! and I would be interested in updating the substances dataset (ie "substances.json").

sorry if I missed any build options, scripts, etc, im very very new to gradle and after looking around a bit, I failed to find anything.

lots of love,
Xea

**Comment by isaakhanimann** [comment]
The way to update it is to update the data in PsychonautWiki and then the changes will automatically be in the next release.

**Comment by Im-0xea** [comment]
well, im already building it from source, which is working fine for me, I have already done some small fixes and would not like to wait till the next release to fix some substances, seams somehow the content of substances.json got updated now.

anyhow thanks for your timely reply!

**Comment by isaakhanimann** [comment]
I don’t understand what you are suggesting. The substances.json is created in a separate repo: https://github.com/isaakhanimann/substance-scraping
In that repo it basically fetches the data of the PsychonautWiki API and then transforms it a bit. But the important thing to note is that as much as possible PsychonautWiki is the source of truth through the API.

**Comment by Im-0xea** [comment]
> I don’t understand what you are suggesting. The substances.json is created in a separate repo: https://github.com/isaakhanimann/substance-scraping In that repo it basically fetches the data of the PsychonautWiki API and then transforms it a bit. But the important thing to note is that as much as possible PsychonautWiki is the source of truth through the API.

that is everything I needed to know!, thank you very much!

and thank you again for your amazing work, I use your app every day
