### ISSUE TITLE
DXM in freebase vs hydrobromide

### ISSUE THREAD

**Issue by davidhedlund** [isaakhanimann/psychonautwiki-journal-android#3]
[DXM](https://psychonautwiki.org/wiki/DXM): "It should be noted that DXM in freebase form (as found in Robocough RoboTablets) is around 27-37% more potent than its hydrobromide form due to a higher concentration of DXM by weight. One should take this into account when calculating their dose to avoid a potential overdose."

Title: Same as the title of this issue
Author: Dingbatdoofus
Source: https://psychonautwiki.org/w/index.php?title=Dextromethorphan&diff=144192&oldid=143981
License: Creative Commons Attribution-ShareAlike 4.0 International

**Comment by isaakhanimann** [comment]
Added.
