### ISSUE TITLE
Blotters: It's recommended to always swallow blotters

### ISSUE THREAD

**Issue by davidhedlund** [isaakhanimann/psychonautwiki-journal-android#4]
Swallowing blotters will most likely inactivate substances that not active orally (like 25I-NBOMe).

See https://psychonautwiki.org/wiki/Unique_substance_warnings#Dosage_form that I wrote.

Title: Same as the title of this issue
Author: David Hedlund
Source: https://psychonautwiki.org/wiki/Unique_substance_warnings
License: Creative Commons Attribution-ShareAlike 4.0 International

**Comment by isaakhanimann** [comment]
In the safer use text of LSD it already explains this.

**Comment by davidhedlund** [comment]
> In the safer use text of LSD it already explains this.

LSD != blotter

**Comment by davidhedlund** [comment]
Blotter paper is a dosage form for any substance, not specifically for LSD.

**Comment by isaakhanimann** [comment]
Which other substances are commonly sold on blotters? I would need a list of substance names.

**Comment by davidhedlund** [comment]
> If users are aware that its not LSD then they probably don't want to inactivate the substance.

You don't know if your blotters only contains LSD even if they are tested, they can still be laced. A safe way to inactive NBOMe is simply to swallow them.

**Comment by isaakhanimann** [comment]
I don‘t think you understood how this information is presented in the app.

**Comment by davidhedlund** [comment]
> I don‘t think you understood how this information is presented in the app.

That's true.
