### ISSUE TITLE
Methadone timeline broken

### ISSUE THREAD

**Issue by homerjunior** [isaakhanimann/psychonautwiki-journal-android#40]
If you put a Methadone recording in the line is flat and one hour long[]()![Screenshot_20240131-100601.png](https://github.com/isaakhanimann/psychonautwiki-journal-android/assets/131698580/0b56eb1b-283d-42a2-9a81-e2219f31332e)

**Comment by isaakhanimann** [comment]
Thats because in the Wiki methadone is missing the comeup and offset. If you add those durations there it will be in the next release of the app.
