### ISSUE TITLE
Hydroxyzine (brand name Atarax, and Vistaril) is never safe to inject

### ISSUE THREAD

**Issue by davidhedlund** [isaakhanimann/psychonautwiki-journal-android#44]
Hydroxyzine (brand name Atarax, and Vistaril) "The drug is not recommended for SC, IA, or SC administration because of adverse reactions that have occurred after its administration via these routes." - https://www.sciencedirect.com/topics/neuroscience/hydroxyzine

**Comment by isaakhanimann** [comment]
This substance is not in the app.
