### ISSUE TITLE
Route of administration: Nasal administration: Nasal septum perforation

### ISSUE THREAD

**Issue by davidhedlund** [isaakhanimann/psychonautwiki-journal-android#47]
# Description
From https://en.wikipedia.org/wiki/Nasal_septum_perforation

![image](https://github.com/isaakhanimann/psychonautwiki-journal-android/assets/6416073/9eeb35d5-5fe5-427b-ac65-ffe02e637938)

A nasal septum perforation is a medical condition in which the nasal septum, the bony/cartilaginous wall dividing the nasal cavities, develops a hole or fissure.

Non-infective causes include cocaine abuse, chronic use of topical nasal decongestants, methamphetamine.

# Suggestion
It would be useful if the app warned people about **Nasal septum perforation** when they choose "Insufflation" as route of administration.

**Comment by isaakhanimann** [comment]
In the safer tab there is an explanation of the different routes and their drawbacks. There is also a video explaining safer sniffing.
Its very important that users can log ingestions quickly without too many hurdles. I can't have them acknowledge too many safer use dislaimers without sacrificing usability.
There are also many other substance specific things that users need to think about.

**Comment by davidhedlund** [comment]
> In the safer tab there is an explanation of the different routes and their drawbacks... I can't have them acknowledge too many safer use dislaimers without sacrificing usability.

Why not add "Nasal septum perforation" to the intranasal route? It is one of the physical major disorder caused by substance abuse, but very few people are aware of this medical term.

**Comment by davidhedlund** [comment]
https://en.wikipedia.org/wiki/Nasal_septum_perforation is the _only_ Wikipedia article about a nose disorder cause by chronic insufflation of substances.

**Comment by isaakhanimann** [comment]
Are you suggesting to update this text? ![image](https://github.com/isaakhanimann/psychonautwiki-journal-android/assets/31287934/ab3dc71f-ed9d-4ca6-82a4-8a55ef85a938)
