### ISSUE TITLE
App does not take shared pathways into consideration when combining substances

### ISSUE THREAD

**Issue by smiba** [isaakhanimann/psychonautwiki-journal-android#50]
(I know this is a really difficult one to implement simply because we don't have a central repository where we can get this information from at the moment)

Right now the application does not take shared pathways into consideration when combining substances, leading to the graph indicating that the effects of said substance are supposed to have worn-off by now, even though they absolutely are not. 

An example of this is combining Alcohol and GBL/GHB, both sharing the same Alcohol dehydrogenase pathway in the body. This leads to the effects of both substances being heavier (which I guess is properly warned for as this combination shows the 3 warning symbols), but not that it will take longer for both to leave your system.

**Comment by isaakhanimann** [comment]
You are right, there is no data to quantitatively implement this. So I will close this issue.
