### ISSUE TITLE
Percentage purity is backwards

### ISSUE THREAD

**Issue by anaisbetts** [isaakhanimann/psychonautwiki-journal-android#51]
If I take 10g of a 50% pure substance, the amount I took was 5g, not 20g. This is a very Odd way to represent purity - people measure the weight of the actual substance they consume.

**Comment by isaakhanimann** [comment]
Its better to decide how much pure substance you consume first and then figure out what you have to weigh. Or are you like: "let me take 120mg of that powder with 18% Heroin. How much is that in pure form". If you want to track different units in the first place then its better to create a custom unit anyway.

**Comment by isaakhanimann** [comment]
I already addeda change which is not released yet where it says "pure mg" vs "impure mg"
