### ISSUE TITLE
Make icon material you

### ISSUE THREAD

**Issue by bl4ze1g** [isaakhanimann/psychonautwiki-journal-android#54]
I'd love to be able to have a material you version of the icon on my home screen

**Comment by isaakhanimann** [comment]
Feel free to create a PR for it

**Comment by bl4xe** [comment]
I have never coded anything like this and have no clue how adaptive icons work even after reading quite a bit into it, here's an svg i created of the icon that is monochromatic and that i think could work as an adaptive icon:
![Untitled](https://github.com/isaakhanimann/psychonautwiki-journal-android/assets/96691738/645d2001-dd2e-4592-8019-3450389654ee)
![Untitled](https://github.com/isaakhanimann/psychonautwiki-journal-android/assets/96691738/0117b18a-88ab-465d-ac2c-a61b81e8943b)

**Comment by isaakhanimann** [comment]
I dont know how it works yet either. I wrote it down so I dont forget about it if I have time. Thanks for creating these assets

**Comment by isaakhanimann** [comment]
I just merged the change to support adaptive icons
