### ISSUE TITLE
v9.0 keeps stopping

### ISSUE THREAD

**Issue by bl4ze1g** [isaakhanimann/psychonautwiki-journal-android#63]
Just upgraded and can't open App anymore, tried force stopping and clearing cache, tried to install v9 through both obtainium and shizuku and github releases, both result in the same behaviour. Will have to downgrade until fixed

**Comment by isaakhanimann** [comment]
Does a fresh install also crash for you?

**Comment by bl4ze1g** [comment]
i don't want to lose any not yet backed up data so i don't want to try

**Comment by isaakhanimann** [comment]
Makes sense. I will fix it asap

**Comment by kescherCode** [comment]
Also happens on fresh install, tested on secondary device.

**Comment by kescherCode** [comment]
```
java.lang.IllegalArgumentException: Cannot find class with name "com.isaakhanimann.journal.data.substances.AdministrationRoute". Ensure that the serialName for this argument is the default fully qualified name
```

**Comment by isaakhanimann** [comment]
Thank you very much. I think this is the issue: https://issuetracker.google.com/issues/358137294?hl=bn
I think its fixed now.
Can you let me know if v9.1 is working for you?

**Comment by kescherCode** [comment]
Yep, 9.1 fixes this.
